# service registers under this name
spring:
  application:
    name: service1

#discover ser
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 2222
